version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '3000:3000'
      - '13306:3306'
volumes:
  db_data:
